export const SET_USER = 'SET_USER';
export const GET_ERRORS = 'GET_ERRORS';
export const SET_TEACHER = 'SET_TEACHER';
export const SET_PREFERRED_TEACHER = 'SET_PREFERRED_TEACHER'
export const SET_MY_PREFERRED_TEACHER = 'SET_MY_PREFERRED_TEACHER'